version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: 111
    volumes:
      - ./db_data:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:5.1.0
    restart: always
    ports:
      - 13000:3000
    volumes:
      - ./grafana_data:/var/lib/grafana
  adminer:
    image: adminer
    restart: always
    ports:
      - 9081:8080
